[dependencies]
bootloader = "0.9"
volatile = "0.2"
spin = "0.9"

[build-dependencies]
bootimage = "0.10"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-bootloader"
